#! /usr/bin/env bash

func test_data_process(){
    challenge_group=${1}
    challenge_number=${2}
    solution_file_path=${3}

    # Set up test environment
    test_path=".test/${challenge_group}/${challenge_number}"
    challenge_path=".test/${challenge_group}/${challenge_number}"
    rm -rf ${test_path}
    mkdir -p ${test_path}
    cp -r "${challenge_path}/*" ${test_path}
    cd ${test_path}
    # TODO: If exists, execute setup

    chmod +x ${solution_file_path}
    # TODO: Handle this command 'winning' or 'losing'
    sdiff <(cat start | ${solution_file_path}) finish
}
# Prepare test directory
rm -rf test/cut/1
mkdir -p test/cut/1
cp challenges/cut/1/* test/cut/1/
cp ${1} test/cut/1/solve
chmod +x test/cut/1/solve
cd test/cut/1

./setup
if sdiff <(./solve) target; then
    echo "Cut challenge 1 passed!"
else
    echo "Cut challenge 1 FAILED!"
    echo "Your output is above on the left, compared with the target on the right."
fi
