#! /usr/bin/env bash

# Prepare test directory
rm -rf test/cut/1
mkdir -p test/cut/1
cp challenges/cut/1/* test/cut/1/
cp ${1} test/cut/1/solve
chmod +x test/cut/1/solve
cd test/cut/1

./setup
if sdiff <(./solve) target; then
    echo "Cut challenge 1 passed!"
else
    echo "Cut challenge 1 FAILED!"
    echo "Your output is above on the left, compared with the target on the right."
fi
